require 'arelastic/aggregations/aggregation'
require 'arelastic/aggregations/bucket'

require 'arelastic/aggregations/date_histogram'
require 'arelastic/aggregations/filter'
require 'arelastic/aggregations/filters'
require 'arelastic/aggregations/histogram'
require 'arelastic/aggregations/min'
require 'arelastic/aggregations/missing'
require 'arelastic/aggregations/nested'
require 'arelastic/aggregations/range'
require 'arelastic/aggregations/reverse_nested'
require 'arelastic/aggregations/sampler'
require 'arelastic/aggregations/terms'
