require 'arelastic/filters/filter'

require 'arelastic/filters/and'
require 'arelastic/filters/exists'
require 'arelastic/filters/ids'
require 'arelastic/filters/limit'
require 'arelastic/filters/missing'
require 'arelastic/filters/not'
require 'arelastic/filters/or'
require 'arelastic/filters/prefix'
require 'arelastic/filters/range'
require 'arelastic/filters/term'
require 'arelastic/filters/terms'
