require 'arelastic/queries/query'

require 'arelastic/queries/bool'
require 'arelastic/queries/constant_score'
require 'arelastic/queries/field'
require 'arelastic/queries/match'
require 'arelastic/queries/match_all'
require 'arelastic/queries/match_none'
require 'arelastic/queries/multi_match'
require 'arelastic/queries/nested'
require 'arelastic/queries/prefix'
require 'arelastic/queries/query_string'
require 'arelastic/queries/simple_query_string'
require 'arelastic/queries/terms'
require 'arelastic/queries/term'
require 'arelastic/queries/wildcard'
