name: Ruby
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.4.10', '2.5.9', '2.6.9', '2.7.5', '3.0.3', '3.1.0' ]
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Install Ruby, bundler and the bundle
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
